import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from './SessionProviderWrapper';
import StoreProviderWrapper from './Providers';
import { useParams } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const name = useParams()
  if(name.startsWith('auth')){
    return (
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    );
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProviderWrapper>
          <SessionProviderWrapper>
            {children}
          </SessionProviderWrapper>
        </StoreProviderWrapper>
      </body>
    </html>
  );
}
